### ISSUE TITLE
Unity/Lomiri crashes when starting container

### ISSUE THREAD

**Issue by joelselvaraj** [Anbox-halium/anbox-halium#3]
Hey. Thanks for your work on this! I understand that this is in the early stages of development. Just a heads up on the issue I faced in Xiaomi Poco F1 (Halium9, UT). 

When I started the container, the Unity8 seemingly crashed and restarted itself every 5 secs or so. Checking at the logs, it appears the `android.hardware.graphics.composer@2.1-service` crashes. Some binder failures happen. I have attached the syslog for your reference. 
[anbox-crash.txt](https://github.com/Anbox-halium/anbox-halium/files/6652390/anbox-crash.txt)
The anbox container seem to be running fine when i checked `sudo lxc-info anbox`

Here is the generated anbox.prop file for my Poco F1.
[anbox.prop.txt](https://github.com/Anbox-halium/anbox-halium/files/6652397/anbox.prop.txt)
Some properties seems to be missing.

I am willing to test out stuffs. Let me know if you need any extra logs. I will be sure to fetch them for you to debug. I am wondering if i can trace the crash.

**Comment by erfanoabdi** [comment]
Thanks, on halium devices we're waiting for xenial_-_android9_-_wayland branch to merge on UT to have working wayland.

**Comment by joelselvaraj** [comment]
Ah. I remember seeing those changes for Mir in your repo. Is there deb package available for Mir for that branch?

**Comment by erfanoabdi** [comment]
highly recommended to wait for merge but 
`sudo ubports-qa install xenial_-_android9_-_wayland`
can install it, be aware this may break android lxc config
also set Pin-Priority to 2012 from /etc/apt/preferences.d/ubports-xenial_-_android9_-_wayland.pref

**Comment by joelselvaraj** [comment]
Understood. I will give them a try. Its just a test device.

**Comment by pagnchanak** [comment]
> highly recommended to wait for merge but
> `sudo ubports-qa install xenial_-_android9_-_wayland`
> can install it, be aware this may break android lxc config
> also set Pin-Priority to 2012 from /etc/apt/preferences.d/ubports-xenial_-_android9_-_wayland.pref

With this I got to Lineage setup screen, but touch is not responding, screen scaling also not correctly. I'm on UT on xiaomi perseus.

**Comment by erfanoabdi** [comment]
> With this I got to Lineage setup screen, but touch is not responding, screen scaling also not correctly. I'm on UT on xiaomi perseus.

for scaling edit `ro.sf.lcd_density` from "/home/anbox/anbox.prop"
and about touch, just restart container

**Comment by joelselvaraj** [comment]
@erfanoabdi Unity8 doesnt crash now. Lineage loads up. But, the setup wizard keeps crashing and i cant finish the setup and go to the home screen. 

Apart from that, there is a like a 1 inch black bar in bottom and lineage displays only above that.

**Comment by joelselvaraj** [comment]
oh well, changing the display height in anbox prop fixed the black bar

**Comment by joelselvaraj** [comment]
Here is the full logcat on the anbox container for reference: https://paste.ubuntu.com/p/tmDqt3rvyr/

I think the issue is
```
06-25 17:34:50.665   211  1488 I ActivityTaskManager: START u0 {act=org.lineageos.setupwizard.LINEAGE_WELCOME flg=0x4000000 cmp=org.lineageos.setupwizard/.WelcomeActivity (has extras)} from uid 1000
06-25 17:34:50.670  1700  1700 D AndroidRuntime: Shutting down VM
06-25 17:34:50.671  1700  1700 E AndroidRuntime: FATAL EXCEPTION: main
06-25 17:34:50.671  1700  1700 E AndroidRuntime: Process: org.lineageos.setupwizard, PID: 1700
06-25 17:34:50.671  1700  1700 E AndroidRuntime: java.lang.IllegalStateException: Activity top position already set to onTop=false
06-25 17:34:50.671  1700  1700 E AndroidRuntime: 	at android.app.ActivityThread.handleTopResumedActivityChanged(ActivityThread.java:4370)
06-25 17:34:50.671  1700  1700 E AndroidRuntime: 	at android.app.servertransaction.TopResumedActivityChangeItem.execute(TopResumedActivityChangeItem.java:39)
06-25 17:34:50.671  1700  1700 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
06-25 17:34:50.671  1700  1700 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
06-25 17:34:50.671  1700  1700 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
06-25 17:34:50.671  1700  1700 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
06-25 17:34:50.671  1700  1700 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
06-25 17:34:50.671  1700  1700 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
06-25 17:34:50.671  1700  1700 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-25 17:34:50.671  1700  1700 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
06-25 17:34:50.671  1700  1700 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
06-25 17:34:50.673   211   231 I ActivityManager: Showing crash dialog for package org.lineageos.setupwizard u0
06-25 17:34:50.685   211  1296 I Adreno  : QUALCOMM build                   : 84ea314, I37527e3d62
06-25 17:34:50.685   211  1296 I Adreno  : Build Date                       : 01/12/19
06-25 17:34:50.685   211  1296 I Adreno  : OpenGL ES Shader Compiler Version: EV031.25.03.02
06-25 17:34:50.685   211  1296 I Adreno  : Local Branch                     : 
06-25 17:34:50.685   211  1296 I Adreno  : Remote Branch                    : 
06-25 17:34:50.685   211  1296 I Adreno  : Remote Branch                    : 
06-25 17:34:50.685   211  1296 I Adreno  : Reconstruct Branch               : 
06-25 17:34:50.686   211  1296 I Adreno  : Build Config                     : S P 6.0.7 AArch64
06-25 17:34:50.688   211  1296 I Adreno  : PFP: 0x016ee180, ME: 0x00000000
06-25 17:34:50.689   211  1296 E libEGL  : Driver indicates EGL 1.5 support, but does not have a critical API
06-25 17:34:51.167   211   233 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{91099f1 u0 org.lineageos.setupwizard/.wizardmanager.WizardManager t93 f}
06-25 17:34:51.167   211   233 W ActivityTaskManager: Activity pause timeout for ActivityRecord{91099f1 u0 org.lineageos.setupwizard/.wizardmanager.WizardManager t93 f}
```

The launcher also seems to crash with
```
06-25 17:34:52.569   211   240 I ActivityManager: Start proc 1727:com.android.launcher3/u0a91 for service {com.android.launcher3/com.android.launcher3.notification.NotificationListener}
06-25 17:34:52.581  1727  1727 I droid.launcher: The ClassLoaderContext is a special shared library.
06-25 17:34:52.590  1727  1727 D AndroidRuntime: Shutting down VM
06-25 17:34:52.590  1727  1727 E AndroidRuntime: FATAL EXCEPTION: main
06-25 17:34:52.590  1727  1727 E AndroidRuntime: PID: 1727
06-25 17:34:52.590  1727  1727 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.app.Instrumentation.onException(java.lang.Object, java.lang.Throwable)' on a null object reference
06-25 17:34:52.590  1727  1727 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3962)
06-25 17:34:52.590  1727  1727 E AndroidRuntime: 	at android.app.ActivityThread.access$1500(ActivityThread.java:219)
06-25 17:34:52.590  1727  1727 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1875)
06-25 17:34:52.590  1727  1727 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
06-25 17:34:52.590  1727  1727 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
06-25 17:34:52.590  1727  1727 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
06-25 17:34:52.590  1727  1727 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-25 17:34:52.590  1727  1727 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
06-25 17:34:52.590  1727  1727 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
06-25 17:34:52.592  1727  1727 I Process : Sending signal. PID: 1727 SIG: 9
06-25 17:34:52.601   211  1573 I ActivityManager: Process com.android.launcher3 (pid 1727) has died: fore BFGS
06-25 17:34:52.601    58    58 I Zygote  : Process 1727 exited due to signal 9 (Killed)
```

**Comment by erfanoabdi** [comment]
@joelselvaraj apply https://gitlab.com/ubports/community-ports/android9/xiaomi-redmi-note-7/kernel-xiaomi-lavender/-/commit/fc678776089a9d3fac6a47c2bb8f5053bbd824a0

**Comment by L-as** [comment]
Seems to possibly be the same as #340 ?
